name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    step:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello-world.txt)"
